### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by Carl-M** [mbouclas/loopback-connector-mailgun#1]
Does the connector handle attachments? a brief look seems to suggest not.

Thanks,

**Comment by mbouclas** [comment]
I have added the option to add attachments, custom variables and custom headers. Please check the README for example.

**Comment by Carl-M** [comment]
Thanks for updating the library! 
Can this to be used to send an attachment from a buffer/stream rather than a file? I am using a PDF library to generate a PDF first which outputs via pipe to a stream.

With out the connector I've used mailgun.js to send with an attachment like this :

```
var buffer = Buffer.concat(memStream.queue);
var attachment = new Mailgun.Attachment({data: buffer, filename: "attachment.pdf"});
```

**Comment by mbouclas** [comment]
Based on mailgun-js, i changed the attachments to accept file streams but also convert strings into streams. If you check the README you will see an example of attaching the filestream. In theory, it should work with the your buffer setup as well. You need to pass the content-type though cause in my tests, mailgun rejected attachments without it.

Hope this helps

**Comment by Carl-M** [comment]
Super, just tried it out, works fine. Thank you for your work!
