### ISSUE TITLE
[Issue] Missing callback argument on Mailgun's Mailer.send method

### ISSUE THREAD

**Issue by saintc0d3r** [mbouclas/loopback-connector-mailgun#2]
## Synopsis:

When a loopback app use **loopback-connector-mailgun** for sending a verification email through calling **User** model's **verify** method with callback function, placed in **Email.verify** method's 2nd argument, the callback function does not execute. 
## Replication Steps:
1. Create a new model which is inherited from loopback's **User** model
   ![image](https://cloud.githubusercontent.com/assets/1336147/14168388/aca53478-f754-11e5-82fa-42f64767ab43.png)
2. Install Loopback mailgun email connector. Example can be seen as follow:
   ![image](https://cloud.githubusercontent.com/assets/1336147/14168347/659d2586-f754-11e5-83d8-13252abdf7da.png)
   ![image](https://cloud.githubusercontent.com/assets/1336147/14168372/952e0dba-f754-11e5-9d8a-3ec8c60248af.png)
3. On the new model, Implement **after remote** hook for **create** method. In the method, call the userInstance's **verify** method with callback function in its 2nd argument. Put a breakpoint in this line.
4. Run loopback explorer and call /users POST method. Confirm that the verification mail is sent successfully but it never enter the callback method.

![image](https://cloud.githubusercontent.com/assets/1336147/14168267/f4b61c88-f753-11e5-930d-4cd1ff7aac5b.png)
## Source of problem:

This issue happened because in **loopback-connector-mailgun**'s mailgun.js, the Mailer.send method does not accept callback function as its 2nd argument. Therefore, passed in callback on loopback's Email.send method , will not be called.
## Suggested Fix:

Add callback function as Mailer.send method's 2nd argument and has the callback invoked within the Promise's resolve & reject functions so that Mailer.send support both returning the result in a Promise & in a Callback.
![image](https://cloud.githubusercontent.com/assets/1336147/14173123/a3d28656-f76e-11e5-9669-5624f4d0c924.png)

**Comment by mbouclas** [comment]
Ok, done, i've added the callback function

**Comment by saintc0d3r** [comment]
Awesome ! Thanks a lot, mate.

Cheers.
