### ISSUE TITLE
BCC not supported?

### ISSUE THREAD

**Issue by denkan** [mbouclas/loopback-connector-mailgun#6]
Using your connector - nice work!

But I am having trouble getting bcc to send. 

Snippet:
```
      const message = {
        to: EMAIL_CONFIG.to,
        bcc: post.emailSendCopyTo,
        from: EMAIL_CONFIG.from,
        subject: EMAIL_CONFIG.subject,
        html: letter.getLetterAsHtml()
      };
      
      EMAIL.send(message)
      .then((response) => console.log('response',response))
      .catch((err) => console.log('error',err))
```

Is the `bcc` property not supported?

**Comment by mbouclas** [comment]
I've added bcc and cc options. It should work

**Comment by denkan** [comment]
Thanks for quick response/action.

But the changes might have broken the api: 
I'm getting `{"message":"'cc' parameter is not a valid address. please check documentation"}` as response from mailgun - meaning, Mailgun consume the parameter even if its set to null?

Change line 100-101 to:
```
        if(options.cc) {
                mailgunMessage.cc = options.cc;
        }
        if(options.bcc) {
                mailgunMessage.bcc = options.bcc;
        }
```
?

**Comment by mbouclas** [comment]
that. or it could be that the version of mailgun-js we're using did not support cc and bcc. I changed it to the if statement but can't test it now. If you get it working, submit a PR and i'll merge right away

**Comment by denkan** [comment]
I actually switched to mailgun-js directly and they had the same problem when I specified bcc as null. Easy to adjust on my part though. 

I'm a bit in a hurry so I'll just leave you with the conclusion that we need the if():s :) 

Thanks for your time and work!
