### ISSUE TITLE
Update mailgun-js package to last version

### ISSUE THREAD

**Issue by alltouch** [mbouclas/loopback-connector-mailgun#7]
@mbouclas Could you please update it latest version?

**Comment by mbouclas** [comment]
I would have to do some testing first in case the latest version breaks anything. If you can't wait, please submit a PR after testing it with the latest version and i'll push it

**Comment by alltouch** [comment]
I am using just simple send email.. I will not be able to test all other features.
I will provide feedback for simple emails soon.

**Comment by alltouch** [comment]
I tested, simple email sending and with attached is working properly.

**Comment by mbouclas** [comment]
Ok, updated to the latest
